# Generated by Django 4.1.7 on 2023-04-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contract", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="description",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Contract Description",
            ),
        ),
    ]
