# Generated by Django 4.1.7 on 2023-04-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contract", "0002_contract_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="data",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
