# Generated by Django 4.1.7 on 2023-04-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contract", "0003_contract_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="data",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
